version: 0.4.1
# https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models
models: gemini-1.5-flash, gemini-1.5-pro, gemini-1.0-pro
default_model: gemini-1.5-flash
oauth_client_id:

knowledge_base:
  embedding_model: text-multilingual-embedding-002
  embedding_search_limit: 5

generative_model_config:
  max_output_tokens: 8192
  temperature: 0.9
  top_p: 0.95

chatbot_role: 