name: Run Python linter and formatter
on:
  push:
    paths-ignore:
      - '**.md'
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'frontend/**'

jobs:
    checks-format:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install uv
          uses: astral-sh/setup-uv@v5
        - name: Install the project
          run: |
            cd backend
            uv sync --all-extras --dev
        - name: Set up Python
          run: |
            cd backend
            uv python install
        - name: Lint with ruff
          run: |
            cd backend
            ruff check .
            ruff format --check .
