name: Test
on:
  push:
    paths-ignore:
      - '**.md'
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'frontend/**'

jobs:
    test:
        env:
            JWT_SECRET_KEY: 1234567890
            FILE_STORAGE_BUCKET: vertex-ai-chat-dev-session-files
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install uv
          uses: astral-sh/setup-uv@v5
        - name: Install the project
          run: uv sync --all-extras --dev
        - name: Set up Python
          run: |
            cd backend
            uv python install
        - name: Authenticate to GCP
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.GCP_SERVICE_KEY }}
        - name: Setup Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v2
          with:
            version: 'latest'
        - name: Test with pytest
          run: |
            cd backend
            coverage run --source=app --module pytest tests --doctest-modules
            coverage report -m
        - name: Coverage Badge
          uses: tj-actions/coverage-badge-py@v2
          with:
            working-directory: 'backend'
        - name: Verify Changed files
          uses: tj-actions/verify-changed-files@v16
          id: verify-changed-files
          with:
            files: |
              backend/coverage.svg
        - name: Commit files
          if: steps.verify-changed-files.outputs.files_changed == 'true'
          run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add backend/coverage.svg
            git commit -m "Updated coverage.svg"
        - name: Push changes
          if: steps.verify-changed-files.outputs.files_changed == 'true'
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.github_token }}
            branch: ${{ github.ref }}