name: Test
on:
  push:
    paths-ignore:
      - '**.md'
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'frontend/**'

jobs:
    test:
        env:
            JWT_SECRET_KEY: 1234567890
            FILE_STORAGE_BUCKET: vertex-ai-chat-dev-session-files
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
                python-version: 3.12
                cache: 'pip'
        - name: Install dependencies
          run: |
            cd backend
            python -m pip install --upgrade pip
            pip install -r requirements-dev.txt
        - name: Authenticate to GCP
          run: |
            echo "${{ secrets.GCP_SERVICE_KEY }}"
            echo "${{ secrets.GCP_SERVICE_KEY }}" > service_account_key.json
            gcloud auth activate-service-account --key-file=service_account_key.json
        - name: Test with pytest
          run: |
            cd backend
            pytest tests/ampf --doctest-modules --junitxml=junit/test-results.xml --cov=app --cov-report=xml --cov-report=html